apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app
data:
  APP_CONFIG_app_baseUrl: {{ .Values.appConfig.app.baseUrl | quote | quote }}
  APP_CONFIG_app_title: {{ .Values.appConfig.app.title | quote | quote }}
  APP_CONFIG_backend_baseUrl: {{ .Values.appConfig.backend.baseUrl | quote | quote }}
  APP_CONFIG_backend_lighthouseHostname: {{ .Values.appConfig.backend.lighthouseHostname | quote | quote }}
  APP_CONFIG_backend_gitOpsHostname: {{ .Values.appConfig.backend.gitOpsHostname | quote | quote }}
  APP_CONFIG_backend_listen: {{ .Values.appConfig.backend.listen | quote | quote }}
  APP_CONFIG_backend_cors_origin: {{ .Values.appConfig.backend.cors.origin | quote | quote }}
  APP_CONFIG_sentry_organization: {{ .Values.appConfig.sentry.organization | quote | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-auth
data:
  AUTH_GOOGLE_CLIENT_ID: {{ .Values.auth.google.clientId }}
  AUTH_GITHUB_CLIENT_ID: {{ .Values.auth.github.clientId }}
  AUTH_GITLAB_CLIENT_ID: {{ .Values.auth.gitlab.clientId }}
  AUTH_OKTA_CLIENT_ID: {{ .Values.auth.okta.clientId }}
  AUTH_OKTA_AUDIENCE: {{ .Values.auth.okta.audience }}
  AUTH_OAUTH2_CLIENT_ID: {{ .Values.auth.oauth2.clientId }}
  AUTH_OAUTH2_AUTH_URL: {{ .Values.auth.oauth2.authUrl }}
  AUTH_OAUTH2_TOKEN_URL: {{ .Values.auth.oauth2.tokenUrl }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-pg
data:
  PGDATABASE: {{ .Values.pg.database }}
  PGUSER: {{ .Values.pg.user }}
  PGPORT: {{ .Values.pg.port | quote }}
  PGHOST: {{ .Values.pg.hostname }}
  PGPATH_TO_CA: {{ .Values.pg.caVolumeMountDir }}/{{ .Values.pg.caFileName }}
