{{- if .Values.externalSecrets.enabled }}
{{/* Verify  that the path ends with a slash*/}}
{{- if not (hasSuffix  "/" (required "externalSecrets.path is required when externalSecrets.enable is true" .Values.externalSecrets.path)) }}
  {{- fail (printf ".Values.externalSecrets.path should end with a `/`, got %s" .Values.externalSecrets.path) }}
{{- end }}
{{- range .Values.externalSecrets.secrets }}
{{- if .key }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations:
  name: {{ .name }}
spec:
  backendType: systemManager
  data:
  - key: {{ printf "%s%s" ( required ".Values.externalSecrets.path is required when external secrets is enabled" $.Values.externalSecrets.path ) .key }}
    name: {{ base .key}}
  region: {{ .region | default $.Values.externalSecrets.defaultRegion }}
{{- end }}
{{- end }}
{{- end }}
