{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.secrets }}
{{- if .key }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations:
  name: {{ .name }}
spec:
  backendType: systemManager
  data:
  {{/* clean avoids double `/` when joining the path and the key name*/}}
  - key: {{ clean (printf "%s/%s" ( required ".Values.externalSecrets.path is required when external secrets is enabled" $.Values.externalSecrets.path ) .key )}}
    name: {{ base .key}}
  region: {{ .region | default $.Values.externalSecrets.defaultRegion }}
{{- end }}
{{- end }}
{{- end }}
