{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-backend
type: Opaque
stringData:
  AUTH_GOOGLE_CLIENT_SECRET: {{ .Values.auth.google.clientSecret }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth.github.clientSecret }}
  AUTH_GITLAB_CLIENT_SECRET: {{ .Values.auth.gitlab.clientSecret }}
  AUTH_OKTA_CLIENT_SECRET: {{ .Values.auth.okta.clientSecret }}
  AUTH_OAUTH2_CLIENT_SECRET: {{ .Values.auth.oauth2.clientSecret }}
  AUTH_AUTH0_CLIENT_SECRET: {{ .Values.auth.auth0.clientSecret }}
  AUTH_MICROSOFT_CLIENT_SECRET: {{ .Values.auth.microsoft.clientSecret }}
  SENTRY_TOKEN: {{ .Values.auth.sentryToken }}
  ROLLBAR_ACCOUNT_TOKEN: {{ .Values.auth.rollbarAccountToken }}
  CIRCLECI_AUTH_TOKEN: {{ .Values.auth.circleciAuthToken }}
  GITHUB_ACCESS_TOKEN: {{ .Values.auth.githubAccessToken }}
  GITLAB_ACCESS_TOKEN: {{ .Values.auth.gitlabAccessToken }}
{{- end }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "backstage.postgresql.fullname" . -}}-certs
  labels:
    app: {{ include "backstage.postgresql.fullname" . }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ include "generateCerts" . | indent 2 }}
{{- end }}
{{- if not .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "backend.postgresql.passwordSecret" . }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  postgresql-password: {{ .Values.appConfig.backend.database.connection.password }}
{{- end }}
{{- if not .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lighthouse.postgresql.passwordSecret" . }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  postgresql-password: {{ .Values.lighthouse.database.connection.password }}
{{- end }}
