apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-service.fullname" . }}
type: Opaque
stringData:
  ROLLBAR_ACCESS_TOKEN: {{ .Values.appConfig.rollbarAccessToken | quote }}
  SENTRY_INGESTION_URL: {{ .Values.appConfig.sentryIngestionUrl | quote }}
