name: Release helm charts

on:
  push:
    branches: [master]

jobs:
  index_charts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Index helm
        run: helm repo index .

      - name: Stage changes
        run: git add --all

      - name: Commit changes
        run: git commit --message "Index charts"
